---
output: html_document
runtime: shiny
editor_options: 
  chunk_output_type: console
---
```{r}
#| include: FALSE
knitr::opts_chunk$set(echo = TRUE) 
library(tidyverse)
library(stringr)
library(rvest)
library(httr)
library(shiny)
```

### NBA Data

```{r}
scrape_nbadata <- function(start_year){
  url <-str_c("https://www.spotrac.com/nba/cap/_/year/", start_year, "/sort/cap_maximum_space", sep = "")

  nba <- read_html(url)

  tables <- html_nodes(nba, css = "table") 

  nba_data <- html_table(tables, header = TRUE, fill = TRUE)[[1]] 

  # Initialize year column
  nba_data$year <- NA

  # Initialize year and counter
  year <- start_year
  counter <- 0

  # Loop over rows
  for(i in seq_len(nrow(nba_data))) {
    # If the next rank is 1 and is not NA, increment the counter
    if(i < nrow(nba_data) && !is.na(nba_data$Rank[i+1]) && nba_data$Rank[i+1] == 1) {
      counter <- counter + 1
    }
    # Calculate the year based on the counter
    nba_data$year[i] <- start_year + counter
  }

  # Remove rows with "Totals" or "Averages"
  nba_data <- nba_data[!rowSums(sapply(nba_data, function(x) grepl("Totals|Averages", x))), ]

  nba_data <- nba_data %>%
    mutate(Team = str_sub(Team, start = 1, end = 3))
  return(nba_data)
}

scrape_nbadata(2023)

# Scrape data for all years
nba <- bind_rows(scrape_nbadata(2017),
          scrape_nbadata(2018),
          scrape_nbadata(2019),
          scrape_nbadata(2020),
          scrape_nbadata(2021),
          scrape_nbadata(2022),
          scrape_nbadata(2023))

# Rename columns
colnames(nba)[1] <- "rank"
colnames(nba)[2] <- "team"
colnames(nba)[4] <- "players_active"
colnames(nba)[5] <- "avg_age_team"
colnames(nba)[6] <- "total_cap_all"
colnames(nba)[7] <- "cap_space_all"
colnames(nba)[9] <- "active"

# Select columns and add new column
nba <- nba |>
  select (year, rank, team, players_active, avg_age_team, total_cap_all, cap_space_all, active) |>
  mutate(WM = "M")
```

```{r}
# Create a data frame with team abbreviations, full names, and cities
nba_teams <- tibble(
  team = c("BOS", "BKN", "NYK", "PHI", "TOR", "CHI", "CLE", "DET", "IND", "MIL", "ATL", "CHA", "MIA", "ORL", "WAS", "DEN", "MIN", "OKC", "POR", "UTA", "GSW", "LAC", "LAL", "PHX", "SAC", "DAL", "HOU", "MEM", "NOP", "SAS"),
  team_name = c("Boston Celtics", "Brooklyn Nets", "New York Knicks", "Philadelphia 76ers", "Toronto Raptors", "Chicago Bulls", "Cleveland Cavaliers", "Detroit Pistons", "Indiana Pacers", "Milwaukee Bucks", "Atlanta Hawks", "Charlotte Hornets", "Miami Heat", "Orlando Magic", "Washington Wizards", "Denver Nuggets", "Minnesota Timberwolves", "Oklahoma City Thunder", "Portland Trail Blazers", "Utah Jazz", "Golden State Warriors", "LA Clippers", "Los Angeles Lakers", "Phoenix Suns", "Sacramento Kings", "Dallas Mavericks", "Houston Rockets", "Memphis Grizzlies", "New Orleans Pelicans", "San Antonio Spurs"),
  city = c("Boston", "Brooklyn", "New York", "Philadelphia", "Toronto", "Chicago", "Cleveland", "Detroit", "Indianapolis", "Milwaukee", "Atlanta", "Charlotte", "Miami", "Orlando", "Washington", "Denver", "Minneapolis", "Oklahoma City", "Portland", "Salt Lake City", "San Francisco", "Los Angeles", "Los Angeles", "Phoenix", "Sacramento", "Dallas", "Houston", "Memphis", "New Orleans", "San Antonio")
)

# Join NBA data with team names and cities
nba <- nba %>%
  left_join(nba_teams, by = "team")
```


### WNBA Data

```{r}
scrape_wnbadata <- function(start_year){
  url <-str_c("https://www.spotrac.com/wnba/cap/_/year/", start_year, "/sort/cap_maximum_space", sep = "")

  wnba <- read_html(url)

  tables <- html_nodes(wnba, css = "table") 

  wnba_data <- html_table(tables, header = TRUE, fill = TRUE)[[1]] 

  # Initialize year column
  wnba_data$year <- NA

  # Initialize year and counter
  year <- start_year
  counter <- 0

  # Loop over rows
  for(i in seq_len(nrow(wnba_data))) {
    # If the next rank is 1 and is not NA, increment the counter
    if(i < nrow(wnba_data) && !is.na(wnba_data$Rank[i+1]) && wnba_data$Rank[i+1] == 1) {
      counter <- counter + 1
    }
    # Calculate the year based on the counter
    wnba_data$year[i] <- start_year + counter
  }

  # Remove rows with "Totals" or "Averages"
  wnba_data <- wnba_data[!rowSums(sapply(wnba_data, function(x) grepl("Totals|Averages", x))), ]

  wnba_data <- wnba_data %>%
    mutate(Team = str_sub(Team, start = 1, end = 3)) %>%
    mutate(Team = case_when(
      Team == "NY\n" ~ "NYL",
      Team == "LA\n" ~ "LAX",
      Team == "LV\n" ~ "LVA",
      TRUE ~ Team
    ))

  return(wnba_data)
}

scrape_wnbadata(2024)

# Scrape data for all years
wnba <- bind_rows(scrape_wnbadata(2018),
          scrape_wnbadata(2019),
          scrape_wnbadata(2020),
          scrape_wnbadata(2021),
          scrape_wnbadata(2022),
          scrape_wnbadata(2023),
          scrape_wnbadata(2024))

# Rename columns
colnames(wnba)[1] <- "rank"
colnames(wnba)[2] <- "team"
colnames(wnba)[3] <- "players_active"
colnames(wnba)[4] <- "avg_age_team"
colnames(wnba)[5] <- "total_cap_all"
colnames(wnba)[6] <- "cap_space_all"
colnames(wnba)[7] <- "active"

# Select columns and add new column
wnba <- wnba |>
  select(year, rank, team, players_active, avg_age_team, total_cap_all, cap_space_all, active) |>
  mutate(WM = "W")

wnba
```

```{r}
# Create a data frame with team abbreviations, full names, and cities
wnba_teams <- tibble(
  team = c("ATL", "CHI", "CON", "IND", "NYL", "WAS", "DAL", "LVA", "LAX", "MIN", "PHX", "SEA"),
  team_name = c("Atlanta Dream", "Chicago Sky", "Connecticut Sun", "Indiana Fever", "New York Liberty", "Washington Mystics", "Dallas Wings", "Las Vegas Aces", "Los Angeles Sparks", "Minnesota Lynx", "Phoenix Mercury", "Seattle Storm"),
  city = c("Atlanta", "Chicago", "Uncasville", "Indianapolis", "New York", "Washington", "Dallas", "Las Vegas", "Los Angeles", "Minneapolis", "Phoenix", "Seattle")
)

# Join WNBA data with team names and cities
wnba <- wnba %>%
  left_join(wnba_teams, by = "team")
```

### Combined data

```{r}
# For NBA data
nba$players_active <- as.character(nba$players_active)

nba$year <- nba$year + 1

# For WNBA data
wnba$players_active <- as.character(wnba$players_active)

# Now bind the rows
all_basketball <- bind_rows(wnba, nba)
```


```{r}

url <- "https://www.espn.com/wnba/team/roster/_/name/chi/chicago-sky"
robotstxt::paths_allowed(url)  

namechi <- read_html(url) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agechi <- read_html(url) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightchi <- read_html(url) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()


urlatl <- "https://www.espn.com/wnba/team/roster/_/name/atl/atlanta-dream"
robotstxt::paths_allowed(urlatl)  
nameatl <- read_html(urlatl) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
ageatl <- read_html(urlatl) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightatl <- read_html(urlatl) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()


urlconn <- "https://www.espn.com/wnba/team/roster/_/name/conn/connecticut-sun"
robotstxt::paths_allowed(urlconn)  
nameconn <- read_html(urlconn) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
ageconn <- read_html(urlconn) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightconn <- read_html(urlconn) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()


urldal <- "https://www.espn.com/wnba/team/roster/_/name/dal/dallas-wings"
robotstxt::paths_allowed(urldal)  
namedal <- read_html(urldal) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agedal <- read_html(urldal) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightdal <- read_html(urldal) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urlind <- "https://www.espn.com/wnba/team/roster/_/name/ind/indiana-fever"
robotstxt::paths_allowed(urlind)  
nameind <- read_html(urlind) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
ageind <- read_html(urlind) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightind <- read_html(urlind) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urllv <- "https://www.espn.com/wnba/team/roster/_/name/lv/las-vegas-aces"
robotstxt::paths_allowed(urllv)  
namelv <- read_html(urllv) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agelv <- read_html(urllv) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightlv <- read_html(urllv) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urlla <- "https://www.espn.com/wnba/team/roster/_/name/la/los-angeles-sparks"
robotstxt::paths_allowed(urlla)  
namela <- read_html(urlla) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agela <- read_html(urlla) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightla <- read_html(urlla) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urlmin <- "https://www.espn.com/wnba/team/roster/_/name/min/minnesota-lynx"
robotstxt::paths_allowed(urlmin)  
namemin <- read_html(urlmin) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agemin <- read_html(urlmin) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightmin <- read_html(urlmin) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urlny <- "https://www.espn.com/wnba/team/roster/_/name/ny/new-york-liberty"
robotstxt::paths_allowed(urlny)  
nameny <- read_html(urlny) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
ageny <- read_html(urlny) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightny <- read_html(urlny) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urlphx <- "https://www.espn.com/wnba/team/roster/_/name/phx/phoenix-mercury"
robotstxt::paths_allowed(urlphx)  
namephx <- read_html(urlphx) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agephx <- read_html(urlphx) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightphx <- read_html(urlphx) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urlsea <- "https://www.espn.com/wnba/team/roster/_/name/sea/seattle-storm"
robotstxt::paths_allowed(urlsea)  
namesea <- read_html(urlsea) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agesea <- read_html(urlsea) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightsea <- read_html(urlsea) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()

urlwsh <- "https://www.espn.com/wnba/team/roster/_/name/wsh/washington-mystics"
robotstxt::paths_allowed(urlwsh)  
namewsh <- read_html(urlwsh) |>
  html_nodes(".inline .AnchorLink") |>
  html_text()
agewsh <- read_html(urlwsh) |>
  html_nodes(".Table__TD:nth-child(3) .inline") |>
  html_text()
heightwsh <- read_html(urlwsh) |>
  html_nodes(".Table__TD:nth-child(4) .inline") |>
  html_text()
nameconn <- append(nameconn, "Tiffany Hayes")
ageconn <- append(ageconn, 33)
heightconn <- append(heightconn, "5' 10\"")
playerfull <- c(nameatl,namechi,nameconn,namedal,nameind,namelv,namela,namemin,nameny,namephx, namesea,namewsh)
agefull <- c(ageatl,agechi,ageconn,agedal,ageind,agelv,agela,agemin,ageny,agephx, agesea,agewsh)
heightfull <-c(heightatl,heightchi,heightconn,heightdal,heightind,heightlv,heightla,heightmin,heightny,heightphx, heightsea,heightwsh) 
```


```{r}
scrape_teamdata <- function(year){
  urlteam <-str_c("https://www.espn.com/wnba/standings/_/season/",year, sep = "")

robotstxt::paths_allowed(urlteam)  

teamm <- read_html(urlteam) |>
  html_nodes(".hide-mobile .AnchorLink") |>
  html_text()

wins <- read_html(urlteam) |>
  html_nodes(".Table__TD:nth-child(1) .stat-cell") |>
  html_text()
wins

losses <- read_html(urlteam) |>
  html_nodes(".Table__TD:nth-child(2) .stat-cell") |>
  html_text()

percent_won <- read_html(urlteam) |>
  html_nodes(".Table__TD:nth-child(3) .stat-cell") |>
  html_text()

home_record <- read_html(urlteam) |>
  html_nodes(".Table__TD:nth-child(5) .stat-cell") |>
  html_text()

away_record <- read_html(urlteam) |>
  html_nodes(".Table__TD:nth-child(6) .stat-cell") |>
  html_text()

conf_record <- read_html(urlteam) |>
  html_nodes(".Table__TD:nth-child(7) .stat-cell") |>
  html_text()

points_per_game <- read_html(urlteam) |>
  html_nodes(".Table__TD:nth-child(8) .stat-cell") |>
  html_text()

tibble(teamm, wins, losses, percent_won, home_record, away_record, conf_record, points_per_game) |>
  mutate(wins=as.double(wins), losses= as.double(losses), points_per_game= as.double(points_per_game), percent_won= as.double(percent_won)) |>
  mutate(year = year, team= teamm) |>
  select(-teamm)
}


scrape_teamdata(2023)


teamstatdata <- bind_rows(scrape_teamdata(2016),
          scrape_teamdata(2017),
          scrape_teamdata(2018), 
          scrape_teamdata(2019), 
          scrape_teamdata(2020), 
          scrape_teamdata(2021), 
          scrape_teamdata(2022), 
          scrape_teamdata(2023))

teamstatdata |>
  count(year) 


scrape_playerdata <- function(year){
  urlplayer <-str_c("https://www.espn.com/wnba/stats/player/_/season/",year,"/seasontype/2", sep = "")

robotstxt::paths_allowed(urlplayer)  

playeryear <- read_html(urlplayer) |>
  html_nodes(".mr7 .AnchorLink") |>
  html_text() 

pointsyear <- read_html(urlplayer) |>
  html_nodes(".Table__TD:nth-child(4)") |>
  html_text()

games_playedyear <- read_html(urlplayer) |>
  html_nodes(".Table__Scroller .Table__TD:nth-child(2)") |>
  html_text() 

rankyear <- read_html(urlplayer) |>
  html_nodes(".Table--fixed-left .Table__TH:nth-child(1) div , .Table--fixed-left .Table__TD:nth-child(1)") |>
  html_text() |>
  tail(n=50)

positionyear <- read_html(urlplayer) |>
  html_nodes(".position") |>
  html_text()|>
  head(n=50)

teamyear <- read_html(urlplayer) |>
  html_nodes(".athleteCell__teamAbbrev") |>
  html_text()|>
  head(n=50)

primary_data <- tibble(playeryear, pointsyear, games_playedyear, rankyear, positionyear, teamyear)

dataage <- tibble(playerfull,agefull,heightfull) |>
  mutate(agefull=(as.double(agefull)-(2024-year)))

left_join(primary_data, dataage, 
                           by = join_by(playeryear== playerfull)) |>
  mutate(heightfull= str_replace(heightfull, '"', "")) |>
  mutate(heightfull= str_replace(heightfull, "'", "")) |>
  separate(heightfull, c("feet", "inches"), " ") |>
  mutate(feet= as.double(feet), inches= as.double(inches)) |>
  mutate(feet_in_inches= feet*12, inches_in_feet= inches/12) |>
  mutate(height_in = feet_in_inches+inches, 
         height_ft= feet+inches_in_feet) |>
  select(-feet, -inches, -feet_in_inches, -inches_in_feet) |>
  mutate(year=year)
}


scrape_playerdata(2023)


playerstatdata <- bind_rows(
          scrape_playerdata(2018), 
          scrape_playerdata(2019), 
          scrape_playerdata(2020), 
          scrape_playerdata(2021), 
          scrape_playerdata(2022), 
          scrape_playerdata(2023))

playerstatdata |>
  count(year) 
```
